### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: logical_ex
template: llama3
cutoff_len: 2500
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8B/full/logical/logical_ex
logging_steps: 100
save_strategy: epoch
save_only_model: true
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
